[versions]
appcompatVersion = "1.7.0"
constraintlayoutVersion = "2.1.4"
gsonVersion = "2.13.2"
ktorVersion = "3.2.3"
okhttp = "5.1.0"
media3Version = "1.8.0"

materialVersion = "1.14.0-alpha06"

[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayoutVersion" }
gson = { module = "com.google.code.gson:gson", version.ref = "gsonVersion" }
media3-ui-compose = { module = "androidx.media3:media3-ui-compose", version.ref = "media3Version" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3Version" }
media3-exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3Version" }
media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3Version" }
okhttp3-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
material = { module = "com.google.android.material:material", version.ref = "materialVersion" }